# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 9115a065142e8fde96f077b253ddcf715ebbfa46ee81633c2e3f10339b792456faeaf518aba017ec555ee3483c94396073f9c8caf8497a8dcebcdaee2e5f7ee2

test:
  domain_name: example.com 
  secret_key_base: c640e83a4b1192c7090e49f921d07f2a9803fc7d9c1331eb5245b00502714435cadb514ba5cdc11060f2c0c4d1a193ca5bcee98b54091ae9e4d2b9b6a735cb78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
